apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: yotify
build:
  local:
    useDockerCLI: true
    push: false
  artifacts:
    - image: yotify-app
      context: backend
      sync:
        # Sync app.rb file, being watch with rack-unreloader
        # or add any other rb file to your application 
        infer:
          - '*.rb'
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
  kubeContext: yotify-mk
