apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: yotify
build:
  local:
    useDockerCLI: true
    push: false
  artifacts:
    - image: yotify-api
      context: api
      sync:
        infer:
          - '*.rb'
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
  kubeContext: yotify-mk
