apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: yotify
build:
  local:
    useDockerCLI: true
    push: false
  artifacts:
    - image: yotify-api
      context: api
      sync:
        infer:
          - '*.rb'
    - image: yotify-b2b
      context: customer_api
      sync:
        infer:
          - '*.rb'
    - image: yotify-backyard
      context: backyard
      sync:
        infer:
          - '*.erb'
          - '*.rb'
          - '*.js'
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
  kubeContext: yotify-mk
