# k8s/backyard.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: yotify-backyard
spec:
  ports:
  - port: 5000
  type: LoadBalancer
  selector:
    app: yotify-backyard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yotify-backyard
spec:
  selector:
    matchLabels:
      app: yotify-backyard
  template:
    metadata:
      labels:
        app: yotify-backyard
    spec:
      containers:
      - name: yotify-backyard
        image: yotify-backyard
        ports:
        - containerPort: 9292
        env:
          - name: RACK_ENV
            value: "development"
